### ISSUE TITLE
De-genericize Deck class

### ISSUE THREAD

**Issue by JacobGinsparg** [arcavios/scooze#183]
## Reasoning:
Certain deck behavior cares about what kinds of cards we're working with at runtime:
  - `deck.total_words()` will only work if the deck contains `OracleCard` or `FullCard`
  - The `DeckNormalizer` needs to know what kind of card to normalize to when the `Deck` is instantiated

## Changes:
`Deck` will no longer be generic:
- `Deck`s will be instantiated with a `card_class` field
- `card_class` will be a loose reminder of the card type the deck was created with
  - NOTE: We can write tickets later if we want to warn against mixing card classes or just hard enforce the class types
 
`DeckPart` will remain generic:
- We don't really care about what cards are in a `DeckPart` at runtime
- Type hints for the cards are the biggest thing for working with `DeckPart` in code

**Comment by fjork3** [comment]
We're going to continue looking into alternatives for this; Python's generic system doesn't seem to be friendly to exactly what we want to do, but keeping Deck genericized does let us make stronger promises about the types of objects we're passing around downstream, which is a very nice benefit that we'd like to keep if possible.

**Comment by iambroadband** [comment]
For future enforcement of types during runtime to check what kinds of Cards are being added to a Deck, we do have the option to use some kind of strict type enforcement package.

**Comment by fjork3** [comment]
Closing as not planned; we want the type-ahead behavior that the current setup gives it, and users can make their own stronger enforcements for runtime behavior.
