### ISSUE TITLE
Use `http.HTTPStatus` enums over raw integers when presenting status codes

### ISSUE THREAD

**Issue by fjork3** [arcavios/scooze#274]

**Comment by iambroadband** [comment]
@fjork3 can you provide an example of where this improvement could be made?

In the CardRouter for instance, we are using raw integers, but they are in HTTPExceptions. Similarly, in the base APIRouter, we are using a raw integer mapped to a message, but that matches the expectation for that class.

https://github.com/arcavios/scooze/blob/dev/src/scooze/routers/card.py

**Comment by iambroadband** [comment]
![image](https://github.com/arcavios/scooze/assets/10965648/3b2e01a0-9ef7-4963-8136-e977c82e8e3f)
is this the expectation?
