### ISSUE TITLE
Upgrade to Pydantic 2.7

### ISSUE THREAD

**Issue by iambroadband** [arcavios/scooze#284]
There were some test failures related to upgrading to Pydantic 2.7.0 because `AliasChoices` is no longer a hashable type.

**Comment by iambroadband** [comment]
https://github.com/pydantic/pydantic/issues/9220

**Comment by iambroadband** [comment]
Pydantic PR https://github.com/pydantic/pydantic/pull/9223

**Comment by cmentzer** [comment]
Is this done? @iambroadband

**Comment by iambroadband** [comment]
No, we are still stuck on 2.6.4. 2.7 doesn't include the hot fix they made to their main branch in the posted PR.
