### ISSUE TITLE
Regression testing against live Scryfall JSON data

### ISSUE THREAD

**Issue by fjork3** [arcavios/scooze#95]
We're heavily following Scryfall's lead on what fields to support; given that, we should have testing in place to catch when fields in their live DB change. We can either download the live versions of the JSON for the cards we're already testing in our unit test suite, and run exactly those same fixtures against the live data as well, or set up a new suite of test cards that we're consistently regression testing.

**Comment by iambroadband** [comment]
My plan for this type of testing is to create a simple .github/workflow that will install scooze, then run 

``` shell
scooze load cards --all > validate_all.log
```

If it generates a log file containing validation errors, then we know it failed on something. As part of this ticket, I think we should improve the logging that the CLI generates too.

**Comment by iambroadband** [comment]
![image](https://github.com/arcavios/scooze/assets/10965648/6e706d91-f10f-44b0-accf-d343011487f1)

7 UTC
11 PST
midnight PDT
